import type { Metadata } from "next";
import "./globals.css";
import logo from '../../assets/agency.png'
import footerLogo from '../../assets/FooterLogo.png'
import Image from "next/image";
import Link from "next/link";
import Insta from '../../assets/instaLogo.png'
import facebook from '../../assets/faceboolLogo.png'
import twitter from '../../assets/twitLogo.png'
import youtube from '../../assets/youtubeLogo.png'
import footerLogoImage from '../../assets/ALADDİN.svg'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <div className="flex flex-row items-center justify-evenly h-24">
            <div className="flex flex-row items-center gap-2 w-36">
              <Image src={logo} alt="logo" width={40} height={40}/>
              <p className="font-bold leading-none">aladdin agency</p>
            </div>
            <div className="flex flex-row items-center gap-12">
              <Link href='#'>Ana səhifə</Link>
              <Link href='#'>Haqqəmızda</Link>
              <Link href='#'>Əlaqə</Link>
              <Link href='#'>Portfolio</Link>
              <Link href='#'>Daha çox</Link>
            </div>
            <div className="flex flex-row gap-4">
              <button className="text-orange-600 border-2 border-orange-600 rounded-lg py-1 px-3">Daxil ol</button>
              <button className="bg-orange-600 text-white rounded-lg py-1 px-3 text-sm">Qeydiyyatdan keç</button>
            </div>
          </div>
        </header>
        {children}
        <footer className="mt-20">
            <div className="flex flex-row items-center p-20 justify-between">
              <div className="flex flex-row items-start justify-between text-gray-700 w-3/5 leading-loose">
                  <div>
                    <p className="text-orange-700 font-semibold mb-3">Catalog</p>
                    <ul>
                      <li className="cursor-pointer">ESWT</li>
                      <li className="cursor-pointer">HILT</li>
                      <li className="cursor-pointer">Skin IQ</li>
                      <li className="cursor-pointer">Rehab Simulators</li>
                      <li className="cursor-pointer">EECP</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-orange-700 font-semibold mb-3">Services</p>
                    <ul>
                      <li className="cursor-pointer">Leasing</li>
                      <li className="cursor-pointer">Consultation</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-orange-700 font-semibold mb-3">About</p>
                    <ul>
                      <li className="cursor-pointer">About us</li>
                      <li className="cursor-pointer">Partners</li>
                      <li className="cursor-pointer">News</li>
                    </ul>
                  </div>
                  <div>
                    <p className="text-orange-700 font-semibold mb-2">Contact</p>
                    <div className="bg-gray-400 h-px w-36 mb-1"></div>
                    <ul>
                      <li>example@gmail.com</li>
                      <li>+994 xx xxx xx xx</li>
                    </ul>
                  </div>
              </div>
              <div className="flex flex-col gap-4">
                <Image src={Insta} alt="instagram" width={40} height={40} className="cursor-pointer"/>
                <Image src={facebook} alt="facebook" width={40} height={40} className="cursor-pointer"/>
                <Image src={twitter} alt="twitter" width={40} height={40} className="cursor-pointer"/>
                <Image src={youtube} alt="youtube" width={40} height={40} className="cursor-pointer"/>
              </div>
            </div>
            <div className="flex flex-row items-end gap-5 p-5 w-auto">
              <Image src={footerLogo} alt="logo" height={210} width={210}/>
              <Image src={footerLogoImage} alt="Aladdin" height={250}/>
            </div>
        </footer>
      </body>
    </html>
  );
}
